MetaDataFormat: "yaml"
theme: "hugo-finisterre"
contentdir: "content"
layoutdir: "layouts"
datadir: "data"
staticdir: "static"
themesdir: "themes"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
pygmentsStyle: "zenburn"
baseURL: "https://www.jonathangilligan.org/"
indexes:
  category: "categories"
  tag: "tags"
title: "Nadjib Achir"
copyright: "&copy; 2024 Nadjib Achir"
canonifyUrls: false
relativeUrls: true
enableRobotsTXT: true
ignoreFiles:
  [
    "~$",
    "^\\.",
    "\\.#",
    "\\.Rmd$",
    "_files$",
    "_cache$",
    "Corel Auto-Preserve$",
  ]

menu:
  main:
    - Name: "Research"
      URL: "/research/"
      Weight: 1
    - Name: "Publications"
      URL: "/publications/"
      Weight: 2
    # - Name: "Teaching"
    #   URL: "/teaching/"
    #   Weight: 3
    - Name: "News"
      URL: "/news/"
      Weight: 4
permalinks:
  post: /post/:year/:month/:day/:slug
  news: /news/:year/:month/:day/:slug
markup:
  defaultMarkdownHandler: goldmark
  blackfriday:
    smartypants: true
    angledQuotes: false
    fractions: false
    smartDashes: true
    latexDashes: true
    hrefTargetBlank: true
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
params:
  AuthorName: "Nadjib Achir"
  copyright:
    year: "2006"
  bio_name: "Nadjib Achir"
  cv_file: "CV_Nadjib_Achir.pdf"
  organization: "University Sorbonne Paris Nord & INRIA"
  fontawesomePro:
    kit: "536cbb4daa"
    key: "sha384-rqn26AG5Pj86AF4SO72RK5fyefcQ/x32DNQfChxWvbXIyXFePlEktwD18fEz+kQU"
  mathjax: true
  mhchem: true
  avatar: "avatar.jpg"
  front_page_img: "/files/headshots/Nadjib.Achir.jpg"
  email: "nadjib.achir@inria.fr"
  pubs_count: 4
  teach_count: 2
  post_count: 2
  news_count: 2
  news_current_months: 12
  news_post_count: 2
  address:
    - '- <a href="https://www.univ-spn.fr/">University Sorbonne Paris Nord</a>,<br/>'
    - "99 Avenue Jean-Baptiste Clément,<br/>"
    - "93430 "
    - "Villetaneuse,<br/>"
    - "France<br/>"
    - '- <a href="https://team.inria.fr/tribe/"> TRiBE research team</a>,<br/>'
    - '<a href="https://www.inria.fr">Inria Saclay - Ile de France</a><br/>'
    - "1 rue Honore d'Estienne d'Orves,<br/>"
    - "Campus de l'Ecole Polytechnique,<br/>"
    - "91120 Palaiseau,"
    - "France"
  social:
    email1:
      priority: 2
      icon: "envelope"
      icon_pack: "fa"
      icon_weight: "s"
      link: "mailto:nadjib.achir@inria.fr"
      text: "nadjib.achir@inria.fr"
    email2:
      priority: 1
      icon: "envelope"
      icon_pack: "fa"
      icon_weight: "s"
      link: "mailto:nadjib.achir@univ-paris13.fr"
      text: "nadjib.achir@univ-paris13.fr"
    orcid:
      priority: 7
      icon: "orcid"
      icon_pack: "ai"
      link: "https://orcid.org/0000-0002-5449-948X"
      text: "0000-0002-5449-948X"
      site: "ORCID:"
      rel_me: yes
    google_scholar:
      priority: 6
      icon: "google-scholar"
      icon_pack: "ai"
      link: "https://scholar.google.fr/citations?user=fL5sKqMAAAAJ&hl=fr"
      text: "Google Scholar"
      rel_me: yes
taxonomies:
  - category: "categories"
  - tag: "tags"
